FROM mcr.microsoft.com/playwright/python:v1.54.0-noble

WORKDIR /app

RUN apt-get update && apt-get upgrade -y && apt-get clean

COPY requirements.txt .
RUN pip install --break-system-packages -r requirements.txt
RUN python -m playwright install --with-deps chromium

# RUN pip install watchfiles

COPY . .

EXPOSE 7860

CMD ["python", "app.py"]


